[package]
name = "sway_mm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.21.3"
swayipc = "3.0.1"
env_logger = "0.10"
